{
 "title": "Rocket.Chat Metrics (Consolidated Version)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "workspaceId",
    "query": {
     "query": "label_values(omnigateway_relay_total_succeeded,workspaceId)"
    }
   },
   {
    "name": "address",
    "query": {
     "query": "label_values(kube_deployment_labels{deployment=\"$deployment\"},label_DeploymentDomain)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(nodejs_active_handles_total,DeploymentName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (version) (rocketchat_info{DeploymentName=\"$deployment\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DeploymentDomain",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (DeploymentDomain) (rocketchat_info{DeploymentName=\"$deployment\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Product",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (Product) (rocketchat_info{DeploymentName=\"$deployment\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Users Online",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_users_online{DeploymentName=\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Users Away",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_users_away{DeploymentName=\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_messages_total{DeploymentName=\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Users",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_users_total{DeploymentName=\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Rooms",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_rooms_total{DeploymentName=\"$deployment\"})"
      }
     ]
    },
    {
     "title": "DDP Users",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rocketchat_ddp_connected_users{DeploymentName=\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Users Diff",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_users_total{DeploymentName=\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Rooms  Diff",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_rooms_total{DeploymentName=\"$deployment\"})"
      }
     ]
    },
    {
     "title": "Messages  Diff",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_messages_total{DeploymentName=\"$deployment\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "increase(rocketchat_metrics_requests{DeploymentName=\"$deployment\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metrics Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "rocketchat_metrics_size{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Handles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 171 },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 171 },
     "targets": [
      {
       "expr": "nodejs_active_requests_total{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Event loop lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 178 },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 178 },
     "targets": [
      {
       "expr": "sum by (space) (nodejs_heap_size_used_bytes{DeploymentName=\"$deployment\"})",
       "legendFormat": "{{space}}"
      }
     ]
    },
    {
     "title": "Per pod heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 185 },
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}} [{{space}}]"
      }
     ]
    },
    {
     "title": "GC - Seconds Running",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 192 },
     "targets": [
      {
       "expr": "sum(increase(nodejs_gc_pause_seconds_total{DeploymentName=\"$deployment\"}[5m])) by (gctype)",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "GC - Bytes Freed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 192 },
     "targets": [
      {
       "expr": "sum(increase(nodejs_gc_reclaimed_bytes_total{DeploymentName=\"$deployment\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DDP Rate Limiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limit by type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 207 },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id!=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by method",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 207 },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id!=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by userId",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 213 },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\"}[5m])) by (user_id)",
       "legendFormat": "{{user_id}}"
      }
     ]
    },
    {
     "title": "Limit by connectionId",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 213 },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id!=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Sent (1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_message_sent{}[5m]))/sum(rocketchat_users_online)/5",
       "legendFormat": "Msg / Online Users"
      },
      {
       "expr": "sum(increase(rocketchat_message_sent{}[5m]))/sum(rocketchat_ddp_connected_users)/5",
       "legendFormat": "Msg / Connected Users"
      }
     ]
    },
    {
     "title": "Online of Connected",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1/(sum(rocketchat_users_away)+sum(rocketchat_users_online))*sum(rocketchat_users_online)"
      }
     ]
    },
    {
     "title": "Online of Active (-open)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(1/rocketchat_users_active{DeploymentName!=\"open\"}*rocketchat_users_online{DeploymentName!=\"open\"})"
      }
     ]
    },
    {
     "title": "Total servers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(min(rocketchat_info) by (DeploymentId))"
      }
     ]
    }
   ]
  },
  {
   "title": "RocketChat Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users Presence",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "avg(rocketchat_users_online{DeploymentName=\"$deployment\"})",
       "legendFormat": "Online"
      },
      {
       "expr": "avg(rocketchat_users_away{DeploymentName=\"$deployment\"})",
       "legendFormat": "Away"
      }
     ]
    },
    {
     "title": "Users & Sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(rocketchat_ddp_connected_users{DeploymentName=\"$deployment\"})",
       "legendFormat": "Connected Users"
      },
      {
       "expr": "sum(rocketchat_ddp_sessions_count{DeploymentName=\"$deployment\"})",
       "legendFormat": "All Sessions"
      },
      {
       "expr": "sum(rocketchat_ddp_sessions_auth{DeploymentName=\"$deployment\"})",
       "legendFormat": "Authenticated Sessions "
      }
     ]
    },
    {
     "title": "Web Socket Connections per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "rocketchat_ddp_connected_users{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Apps Installed / Disabled / Failed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "rocketchat_apps_installed{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}} - installed"
      },
      {
       "expr": "rocketchat_apps_enabled{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}} - enabled"
      },
      {
       "expr": "rocketchat_apps_failed{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}} - failed"
      }
     ]
    },
    {
     "title": "Oplog",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "avg(increase(rocketchat_oplog{DeploymentName=\"$deployment\"}[5m])) by (collection,op)",
       "legendFormat": "{{collection}}/{{op}}"
      }
     ]
    },
    {
     "title": "Oplog By instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "avg(increase(rocketchat_oplog{DeploymentName=\"$deployment\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Oplog Queue",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "rocketchat_oplog_queue{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Push Queue",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "rocketchat_push_queue{DeploymentName=\"$deployment\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Meteor Facts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_facts{DeploymentName=\"$deployment\"}) by (pkg, fact)",
       "legendFormat": "{{pkg}} {{fact}}"
      }
     ]
    },
    {
     "title": "Total of Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "max(rocketchat_users_total{DeploymentName=\"$deployment\"})",
       "legendFormat": "Users"
      }
     ]
    },
    {
     "title": "Total of Rooms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "max(rocketchat_rooms_total{DeploymentName=\"$deployment\"})",
       "legendFormat": "Rooms"
      }
     ]
    },
    {
     "title": "Notifications / Minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_notification_sent{DeploymentName=\"$deployment\"}[5m])) by (notification_type)",
       "legendFormat": "{{notification_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Methods Total Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 209 },
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods{DeploymentName=\"$deployment\"}) by (method) * sum(increase(rocketchat_meteor_methods_count{DeploymentName=\"$deployment\"}[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods{DeploymentName=\"$deployment\"}) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Calls / Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_methods_count{DeploymentName=\"$deployment\"}[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Subscription Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 210 },
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions{DeploymentName=\"$deployment\"}) by (subscription) * sum(increase(rocketchat_meteor_subscriptions_count{DeploymentName=\"$deployment\"}[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions{DeploymentName=\"$deployment\"}) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Calls / Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_subscriptions_count{DeploymentName=\"$deployment\"}[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Callbacks & Hooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Callbacks Total Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 211 },
     "targets": [
      {
       "expr": "sum(rocketchat_callbacks{DeploymentName=\"$deployment\"}) by (callback) * sum(increase(rocketchat_callbacks_count{DeploymentName=\"$deployment\"}[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 219 },
     "targets": [
      {
       "expr": "sum(irate(rocketchat_callbacks{DeploymentName=\"$deployment\"}[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Calls / Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 219 },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_callbacks_count{DeploymentName=\"$deployment\"}[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Hooks Total Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 227 },
     "targets": [
      {
       "expr": "sum(rocketchat_hooks{DeploymentName=\"$deployment\"}) by (hook) * sum(increase(rocketchat_hooks_count{DeploymentName=\"$deployment\"}[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 235 },
     "targets": [
      {
       "expr": "sum(irate(rocketchat_hooks{DeploymentName=\"$deployment\"}[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Calls / Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 235 },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_hooks_count{DeploymentName=\"$deployment\"}[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST API Total Times",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rocketchat_rest_api{DeploymentName=\"$deployment\"}) by (entrypoint) * sum(increase(rocketchat_rest_api_count{DeploymentName=\"$deployment\"}[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(rocketchat_rest_api{DeploymentName=\"$deployment\"}[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Calls / Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_rest_api_count{DeploymentName=\"$deployment\"}[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Omnichannel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Req/s",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by() (rate(omnigateway_relay_total_succeeded{host=\"$address\", source=\"incoming\"}[5m]))\r\n+\r\nsum by( ) (rate(omnigateway_relay_total_failed{host=\"$address\", source=\"incoming\"}[5m]))\r\n",
       "legendFormat": "{{source}} success"
      }
     ]
    },
    {
     "title": "Incoming Time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(\r\n    rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_sum{source=\"incoming\", host=\"$address\"}[5m])\r\n    /\r\n    rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_count{source=\"incoming\", host=\"$address\"}[5m]) > 0\r\n) by (channel, host)",
       "legendFormat": "{{source}} success"
      }
     ]
    },
    {
     "title": "Incoming Errors",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by( ) (rate(omnigateway_relay_total_failed{source=\"incoming\",host=\"$address\"}[5m]))\n/\n(sum by() (rate(omnigateway_relay_total_succeeded{source=\"incoming\",host=\"$address\"}[5m]))+sum by( ) (rate(omnigateway_relay_total_failed{source=\"incoming\",host=\"$address\"}[5m])))\n",
       "legendFormat": "{{source}} success"
      }
     ]
    },
    {
     "title": "Queue Size",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 3, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time({DeploymentName=\"$deployment\"} \n  |= \"Metrics received from subprocess\" \n  | regexp \"queueSize: (?P<queue_size>\\\\d+)\" \n  | unwrap queue_size [10s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Incoming error rate ",
     "type": "text",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 11 },
     "options": {
      "content": "|Attempt 1 | Attempt 2 | Attempt 3 | Attempt 4 | Attempt 5 |\n| -------- | --------- | --------- | --------- | --------- |\n| 0 | 10s | 60s | 5m | 26m |"
     }
    },
    {
     "title": "Incoming error rate ",
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\nsum by (attempt) (rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_count{source=\"incoming\", host=\"$address\", success=\"false\"}[5m]) > 0)\n/\nsum by (attempt) (rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_count{source=\"incoming\", host=\"$address\"}[5m]))\n) ",
       "legendFormat": "Attempt {{attempt}}"
      }
     ]
    },
    {
     "title": "(WA, workspaceId*) Outgoing Req/s",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by() (rate(omnigateway_relay_total_succeeded{workspaceId=\"$workspaceId\", source=\"outgoing\"}[5m]))\r\n+\r\nsum by( ) (rate(omnigateway_relay_total_failed{workspaceId=\"$workspaceId\", source=\"outgoing\"}[5m]))\r\n",
       "legendFormat": "{{source}} success"
      }
     ]
    },
    {
     "title": "(WA, generic) Outgoing Time",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(\r\n    rate(omnigateway_router_http_response_time_milliseconds_sum{route=\"/v1/whatsapp/requests\"}[5m])\r\n    /\r\n    rate(omnigateway_router_http_response_time_milliseconds_count{route=\"/v1/whatsapp/requests\"}[5m]) > 0\r\n) ",
       "legendFormat": "{{source}} success"
      }
     ]
    },
    {
     "title": "(WA, workspaceId*) Outgoing Errors",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by( ) (rate(omnigateway_relay_total_failed{source=\"outgoing\",workspaceId=\"$workspaceId\"}[5m]))\n/\n(sum by() (rate(omnigateway_relay_total_succeeded{source=\"outgoing\",workspaceId=\"$workspaceId\"}[5m]))+sum by( ) (rate(omnigateway_relay_total_failed{source=\"outgoing\",workspaceId=\"$workspaceId\"}[5m])))\n",
       "legendFormat": "{{source}} success"
      }
     ]
    },
    {
     "title": "Omnigateway IO Incoming (req/s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(channel, error, code) (rate(omnigateway_relay_total_failed{host=\"$address\", source=\"incoming\"}[5m]))\r\n",
       "legendFormat": "{{channel}} failed {{error}} {{code}}"
      },
      {
       "expr": "sum by (channel) (rate(omnigateway_relay_total_succeeded{host=\"$address\", source=\"incoming\"}[5m]))",
       "legendFormat": "{{channel}} success"
      }
     ]
    },
    {
     "title": "Omnigateway incoming error rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\r\n    sum by(source, ) (rate(omnigateway_relay_total_failed{host=\"$address\"}[5m]))\r\n    /\r\n    (sum by(source, ) (rate(omnigateway_relay_total_succeeded{host=\"$address\"}[5m])) + sum by(source, ) (rate(omnigateway_relay_total_failed{host=\"$address\"}[5m])))\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "(WA, workspaceId*) Omnigateway IO Outgoing (req/s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(channel, error, code) (rate(omnigateway_relay_total_failed{workspaceId=\"$workspaceId\", source=\"outgoing\"}[5m]))\r\n",
       "legendFormat": "{{channel}} failed {{error}} {{code}}"
      },
      {
       "expr": "sum by (channel) (rate(omnigateway_relay_total_succeeded{workspaceId=\"$workspaceId\", source=\"outgoing\"}[5m]))",
       "legendFormat": "{{channel}}  success"
      }
     ]
    },
    {
     "title": "Queue Size Logs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "max_over_time({DeploymentName=\"$deployment\"} \n  |= \"Metrics received from subprocess\" \n  | regexp \"queueSize: (?P<queue_size>\\\\d+)\" \n  | unwrap queue_size [10s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "AVG Omnigateway incoming processing time [5m] per channel",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_sum{source=\"incoming\", host=\"$address\"}[5m]) / rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_count{source=\"incoming\", host=\"$address\"}[5m]) > 0) by (channel)",
       "legendFormat": "Avg {{channel}}"
      },
      {
       "expr": "max(rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_sum{source=\"incoming\", host=\"$address\"}[5m]) / rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_count{source=\"incoming\", host=\"$address\"}[5m]) > 0) by (channel)",
       "legendFormat": "Max {{channel}}"
      }
     ]
    },
    {
     "title": "MAX Omnigateway incoming processing time [5m] per channel",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_sum{source=\"incoming\", host=\"$address\"}[5m]) / rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_count{source=\"incoming\", host=\"$address\"}[5m]) > 0) by (channel, attempt, host)",
       "legendFormat": "{{channel}}  {{attempt}}/5 max"
      }
     ]
    },
    {
     "title": "OK Omnigateway incoming relay distribution rate per attempt",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "avg(rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_count{source=\"incoming\", host=\"$address\", success=\"true\"}[5m]) > 0) by (channel, attempt)",
       "legendFormat": "{{channel}} {{attempt}}/5"
      }
     ]
    },
    {
     "title": "FAILED Omnigateway incoming relay distribution rate per attempt",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "avg(rate(omnigateway_queue_consumer_processing_time_duration_milliseconds_count{source=\"incoming\", host=\"$address\", success=\"false\"}[5m]) > 0) by (channel, attempt, final)",
       "legendFormat": "{{channel}} {{attempt}}/5"
      }
     ]
    }
   ]
  },
  {
   "title": "Micro Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(moleculer_registry_nodes_total{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Services",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(moleculer_registry_services_total{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Actions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(moleculer_registry_actions_total{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Events",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(moleculer_registry_events_total{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Total calls",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(moleculer_request_total{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Total errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(moleculer_request_error_total{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(irate(moleculer_request_time_rate{namespace=\"$namespace\"}[1m]))"
      }
     ]
    },
    {
     "title": "Rps",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(moleculer_request_total{namespace=\"$namespace\"}[1m]))"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(moleculer_request_time_rate{namespace=\"$namespace\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Action calls",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(moleculer_request_total_rate{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Calls"
      },
      {
       "expr": "sum(irate(moleculer_request_error_total_rate{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Errors"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(moleculer_request_time_sum{namespace=\"$namespace\"}[2m]) / rate(moleculer_request_time_count{namespace=\"$namespace\"}[2m])) by (action, type)",
       "legendFormat": "{{action}} ({{type}})"
      }
     ]
    },
    {
     "title": "Action calls",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "moleculer_request_total_rate{namespace=\"$namespace\"}",
       "legendFormat": "{{action}} ({{nodeID}})"
      }
     ]
    },
    {
     "title": "Current Concurrent Users",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(users_connected{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "DDP Streamer Connected Users",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "users_connected{namespace=\"$namespace\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Error types",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (action, errorName) (irate(moleculer_request_error_total{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{action}} - {{errorName}}"
      }
     ]
    },
    {
     "title": "Broadcasts rate by event",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(moleculer_event_broadcast_local_total{namespace=\"$namespace\"}[5m])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Request totals rate by service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(moleculer_request_total{namespace=\"$namespace\"}[5m])) by (action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Request totals rate by microservice",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(moleculer_request_total{namespace=\"$namespace\"}[5m])) by (kubernetes_name)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Service Request rate by node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "moleculer_request_total_rate{namespace=\"$namespace\"}",
       "legendFormat": "{{nodeID}}-{{action}}"
      }
     ]
    },
    {
     "title": "Request totals by service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(moleculer_request_total{namespace=\"$namespace\"}) by (action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Service Requests by node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "moleculer_request_total{namespace=\"$namespace\"}",
       "legendFormat": "{{nodeID}}-{{action}}"
      }
     ]
    },
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 73 } },
    {
     "title": "Online nodes according to each node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "moleculer_registry_nodes_online_total{namespace=\"$namespace\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Online nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(moleculer_registry_nodes_total{namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  }
 ]
}