{
 "title": "MicroService Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(moleculer_event_broadcast_local_total{namespace=\"$deployment-workspace\", event=\"watch.messages\"})"
    },
    {
     "expr": "sum(rocketchat_message_sent{DeploymentName=\"$deployment-rocketchat-deployment\"})"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(moleculer_registry_actions_total{namespace=\"$deployment-workspace\"})"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(moleculer_registry_events_total{namespace=\"$deployment-workspace\"})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(moleculer_request_time_rate{namespace=\"$deployment-workspace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Rps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(moleculer_request_total{namespace=\"$deployment-workspace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moleculer_request_total_rate{namespace=\"$deployment-workspace\"}[5m]))",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(irate(moleculer_request_error_total_rate{namespace=\"$deployment-workspace\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(moleculer_registry_nodes_total{namespace=\"$deployment-workspace\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(moleculer_registry_services_total{namespace=\"$deployment-workspace\"})"
    }
   ]
  },
  {
   "title": "Total calls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(moleculer_request_total{namespace=\"$deployment-workspace\"})"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(moleculer_request_error_total{namespace=\"$deployment-workspace\"})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(moleculer_request_time_rate{namespace=\"$deployment-workspace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "moleculer_request_total_rate{namespace=\"$deployment-workspace\"}",
     "legendFormat": "{{action}} ({{nodeID}})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(moleculer_request_time_sum{namespace=\"$deployment-workspace\"}[2m]) / rate(moleculer_request_time_count{namespace=\"$deployment-workspace\"}[2m])) by (action, type)",
     "legendFormat": "{{action}} ({{type}})"
    }
   ]
  },
  {
   "title": "Current Concurrent Users",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(users_connected{namespace=\"$deployment-workspace\"})"
    }
   ]
  },
  {
   "title": "DDP Streamer Connected Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "users_connected{namespace=\"$deployment-workspace\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Error types",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (action, errorName) (irate(moleculer_request_error_total{namespace=\"$deployment-workspace\"}[5m]))",
     "legendFormat": "{{action}} - {{errorName}}"
    }
   ]
  },
  {
   "title": "Request totals rate by service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_total{namespace=\"$deployment-workspace\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Request totals rate by microservice",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_total{namespace=\"$deployment-workspace\"}[5m])) by (kubernetes_name)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Service Request rate by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "moleculer_request_total_rate{namespace=\"$deployment-workspace\"}",
     "legendFormat": "{{nodeID}}-{{action}}"
    }
   ]
  },
  {
   "title": "Request totals by service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(moleculer_request_total{namespace=\"$deployment-workspace\"}) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Service Requests by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "moleculer_request_total{namespace=\"$deployment-workspace\"}",
     "legendFormat": "{{nodeID}}-{{action}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Online nodes according to each node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "moleculer_registry_nodes_online_total{namespace=\"$deployment-workspace\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Online nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(moleculer_registry_nodes_total{namespace=\"$deployment-workspace\"})"
    }
   ]
  }
 ]
}